[package]
name = "applejuice_cli"
version = "0.1.0"
edition = "2021"
opt-level = "s"

[dependencies]
progress_bar = "1.0.5"
reqwest = { version = "0.11.18", features = ["blocking"] }
serde_json = "1.0.103"
